import jsYaml from "../../thirdParty/jsYaml/jsYaml.mjs";

export class ConnectorCloudInit {
    constructor(options={}) {
        this.options = options;

        this.publicInterface = options.publicInterface || "eth0";
        this.privateInterface = options.privateInterface || "eth1";
        // Below works for at least Hetzner
        this.privateIp = options.privateIp || `$(ip addr show ${this.privateInterface} | awk '/inet / {print $2}' | cut -d/ -f1)`;
        // For DO we need something like
        // $(curl -s http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)
        this.init = {
          "apt": {
            "sources": {
              "twingate": {
                "source": "deb [trusted=true] https://packages.twingate.com/apt/ /"
              }
            }
          },
          "package_update": true,
          "package_upgrade": true,
          "packages": [],
          "write_files": [],
          "runcmd": []
        };

        this.packages = [
            "twingate-connector",
            "chrony"
        ];
        this.runCommands = [
            [ "systemctl", "daemon-reload" ],
            [ "twingate_refresh_conf" ],
            [ "systemctl", "enable", "twingate-connector.service" ],
            [ "systemctl", "start", "--no-block", "twingate-connector.service" ]
        ];
        // echo "ListenAddress $(ip addr show eth1 | awk '/inet / {print $2}' | cut -d/ -f1)" >> /etc/ssh/sshd_config.d/ListenPrivateIp.conf
        this.files = [
            {
              "content": "#!/bin/bash\nsudo touch /etc/twingate/connector.debug\nsudo systemctl restart twingate-connector\n",
              "path": "/usr/sbin/twingate_enable_debug",
              "permissions": "0755"
            },
            {
              "content": "#!/bin/bash\nsudo rm /etc/twingate/connector.debug\nsudo systemctl restart twingate-connector\n",
              "path": "/usr/sbin/twingate_disable_debug",
              "permissions": "0755"
            },
            {
              "content": "[Service]\nPermissionsStartOnly=true\nExecStartPre=/usr/sbin/twingate_refresh_conf\nEnvironmentFile=\nEnvironmentFile=/etc/twingate/connector.live\n",
              "path": "/etc/systemd/system/twingate-connector.service.d/override.conf"
            }
        ];
    }

    setStaticConfiguration(accountUrl, tokens, extraEnv={}) {
        const conf = {};
        conf["TWINGATE_URL"] = accountUrl;
        conf["TWINGATE_ACCESS_TOKEN"] = tokens.accessToken;
        conf["TWINGATE_REFRESH_TOKEN"] = tokens.refreshToken;
        for ( const [key, value] of Object.entries(extraEnv) ) {
            conf[`TWINGATE_${key}`] = value;
        }
        const content = Object.entries(conf)
            .map( ([key, value]) => `${key.toUpperCase()}=${value}`)
            .join("\n")+"\n";
        this.addFile({
            content,
            path: "/etc/twingate/connector.conf"
        });
        return this;
    }

    setDynamicLabels(labels) {
        const tgLabels = [];
        for (const [label, value] of Object.entries(labels)) {
          if ( value !== null ) tgLabels.push(`export TWINGATE_LABEL_${label.toUpperCase()}=${value}`);
        }

        this.addFile({
            content: `#!/bin/bash\n# This file is called by ExecStartPre in /etc/systemd/system/twingate-connector.service.d/override.conf\necho \"# This file is generated by /usr/sbin/refresh_connector_conf. Do not edit directly." > /etc/twingate/connector.live\n${tgLabels.join("\n")}\nif [[ -f "/etc/twingate/connector.debug" ]];\nthen\n   echo "TWINGATE_LOG_LEVEL=7" >> /etc/twingate/connector.live\nfi\ncat /etc/twingate/connector.conf >> /etc/twingate/connector.live\nenv | grep "^TWINGATE_LABEL_" >> /etc/twingate/connector.live\n`,
            path: "/usr/sbin/twingate_refresh_conf",
            permissions: "0755"
        });
        return this;
    }

    configure(options = {}) {
        options = Object.assign( {
            setupAsNatRouter: false,
            enableFirewall: false,
            autoUpdate: true,
            sshLocalOnly: false,
            autoRebootOnUpdate: true
        }, options);

        if ( options.sshLocalOnly && this.privateIp ) {
            this.runCommands.splice(0, 0,
            ["bash", "-c", `echo "ListenAddress ${this.privateIp}" >> /etc/ssh/sshd_config.d/ListenPrivateIp.conf`],
                  ["systemctl", "restart", "ssh"]
            );
        }
        if ( options.autoUpdate) {
            this.addFile({
                "content": "\nUnattended-Upgrade::Origins-Pattern {\n  \"site=packages.twingate.com\";\n};\n",
                "append": true,
                "path": "/etc/apt/apt.conf.d/50unattended-upgrades"
            });
        }
        if ( options.autoRebootOnUpdate ) {
            this.addFile({
                "content": "\nUnattended-Upgrade::Automatic-Reboot-Time \"02:00\";\n",
                "append": true,
                "path": "/etc/apt/apt.conf.d/50unattended-upgrades"
            });
        }

        if ( options.setupAsNatRouter ) {
            this.packages.push("iptables-persistent");
            // Setup systemd resolve to listen also on the private interface
            this.runCommands.push(
                ["sed", "-i", `s/#DNSStubListenerExtra=/DNSStubListenerExtra=${this.privateIp}/`, "/etc/systemd/resolved.conf"],
                ["systemctl", "restart", "systemd-resolved"],
                ["iptables", "-t", "nat", "-A", "POSTROUTING", "-o", this.publicInterface, "-j", "MASQUERADE"],
                ["iptables", "-A", "FORWARD", "-i", this.publicInterface, "-o", this.privateInterface, "-m", "state", "--state", "RELATED,ESTABLISHED", "-j", "ACCEPT"],
                ["iptables", "-A", "FORWARD", "-i", this.publicInterface, "-o", this.privateInterface, "-j", "ACCEPT"]
                ["iptables-save > /etc/iptables/rules.v4"]
            );
        }

        if ( options.enableFirewall ) {
            this.runCommands.push(
                ["ufw", "default", "deny", "incoming"],
                ["ufw", "default", "allow", "outgoing"],
                ["ufw", "allow", "ssh"],
                ["ufw", "enable"]
            );
        }
        return this;
    }

    addFile(fileObj) {
        this.files.push(fileObj);
    }

    getFileContent() {
        return this.files;
    }


    getPackages() {
        return this.packages;
    }


    getRunCommands() {
        return this.runCommands;
    }

    getConfigJson() {
        return Object.assign({}, this.init, {
            packages: this.getPackages(),
            write_files: this.getFileContent(),
            runcmd: this.getRunCommands()
        });
    }

    getConfig() {
        return `#cloud-config\n${jsYaml.dump(this.getConfigJson(), {lineWidth: 1000})}`
    }
}
