# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    # branches: [main]
    tags:
      - v*.*.*
  # pull_request:
  #   branches: [main]
    

# permissions:
#  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v1

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Test Deno
        run: deno run https://deno.land/std/examples/welcome.ts

      - name: test 2
        run: pwd

      - name: test 3
        run: ls -l
          
      # - name: Execute
      #   uses: ./tg.js@v1
        
      - name: Compile
        run: deno compile --allow-all --import-map ./import_map.json --unstable ./tg.js

      - name: Compress
        run: zip tg-cli-mac.zip ./tg
        
      - name: test 4
        run: ls -l
        
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change

      # - name: Upload Release Asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tg-cli-mac.zip
          asset_name: tg-cli-mac.zip
          tag: ${{ github.ref }}
          body: "This is my release text"
